name: Build and Push Backend Ventas

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Springboot-API-REST
          dockerfile: ./Springboot-API-REST/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:latest
            ${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:buildcache,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_BACKEND_VENTAS }} # IP Pública de la EC2 de Ventas
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Forzamos la descarga de la nueva imagen
            sudo docker pull ${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:latest
            # Detenemos y borramos el contenedor viejo si existe
            sudo docker stop back-ventas  true
            sudo docker rm back-ventas  true
            # Corremos el nuevo con los puertos correctos (8082 para ventas)
            sudo docker run -d --name back-ventas -p 8082:8080 ${{ secrets.DOCKER_HUB_REPO_BACKEND_VENTAS }}:latest